set(GAME_NAME episodic)
target_include_directories(server PUBLIC ../.. ./ ../shared/hl2 ../shared/episodic hl2 episodic)
target_compile_definitions(server PUBLIC HL2_DLL HL2_EPISODIC USES_SAVERESTORE)
target_sources(server PUBLIC
        ai_eventresponse.cpp
        ai_relationship.cpp
        base_gameinterface.cpp
        basegrenade_concussion.cpp
        basegrenade_contact.cpp
        basegrenade_timed.cpp
        grenadethrown.cpp
        h_cycler.cpp
        logic_achievement.cpp
        monstermaker.cpp
        ../shared/hl2/survival_gamerules.cpp
        team_spawnpoint.cpp
        vehicle_choreo_generic.cpp
        ../shared/weapon_parse_default.cpp
        ../shared/episodic/achievements_ep1.cpp
        ../shared/episodic/achievements_ep2.cpp
        ../shared/episodic/achievements_epx.cpp
        hl2/ai_allymanager.cpp
        hl2/ai_behavior_actbusy.cpp
        episodic/ai_behavior_alyx_injured.cpp
        hl2/ai_behavior_functank.cpp
        hl2/ai_behavior_holster.cpp
        hl2/ai_behavior_operator.cpp
        ai_behavior_passenger.cpp
        episodic/ai_behavior_passenger_companion.cpp
        episodic/ai_behavior_passenger_zombie.cpp
        hl2/ai_behavior_police.cpp
        hl2/ai_goal_police.cpp
        hl2/ai_spotlight.cpp
        hl2/antlion_dust.cpp
        hl2/antlion_maker.cpp
        hl2/ar2_explosion.cpp
        basebludgeonweapon.cpp
        hl2/basehlcombatweapon.cpp
        ../shared/hl2/basehlcombatweapon_shared.cpp
        hl2/cbasehelicopter.cpp
        hl2/cbasespriteprojectile.cpp
        hl2/citadel_effects.cpp
        hl2/combine_mine.cpp
        hl2/env_alyxemp.cpp
        hl2/env_headcrabcanister.cpp
        ../shared/hl2/env_headcrabcanister_shared.cpp
        hl2/env_speaker.cpp
        hl2/env_starfield.cpp
        hl2/Func_Monitor.cpp
        hl2/func_recharge.cpp
        hl2/func_tank.cpp
        hl2/grenade_ar2.cpp
        hl2/grenade_bugbait.cpp
        hl2/grenade_frag.cpp
        hl2/grenade_spit.cpp
        hl2/hl2_ai_network.cpp
        hl2/hl2_client.cpp
        hl2/hl2_eventlog.cpp
        ../shared/hl2/hl2_gamerules.cpp
        hl2/hl2_player.cpp
        hl2/hl2_playerlocaldata.cpp
        hl2/hl2_triggers.cpp
        ../shared/hl2/hl2_usermessages.cpp
        ../shared/hl2/hl_gamemovement.cpp
        hl2/hl_playermove.cpp
        hl2/info_darknessmode_lightsource.cpp
        hl2/info_teleporter_countdown.cpp
        hl2/item_ammo.cpp
        hl2/item_battery.cpp
        hl2/item_dynamic_resupply.cpp
        hl2/item_healthkit.cpp
        hl2/item_itemcrate.cpp
        hl2/item_suit.cpp
        hl2/look_door.cpp
        hl2/monster_dummy.cpp
        episodic/npc_advisor.cpp
        hl2/npc_alyx_episodic.cpp
        hl2/npc_antlion.cpp
        hl2/npc_antlionguard.cpp
        hl2/npc_antliongrub.cpp
        hl2/npc_apcdriver.cpp
        hl2/npc_attackchopper.cpp
        hl2/npc_barnacle.cpp
        hl2/npc_barney.cpp
        hl2/npc_basescanner.cpp
        hl2/npc_BaseZombie.cpp
        hl2/npc_breen.cpp
        hl2/npc_bullseye.cpp
        hl2/npc_citizen17.cpp
        episodic/npc_combine_cannon.cpp
        hl2/npc_combine.cpp
        hl2/npc_combinecamera.cpp
        hl2/npc_combinedropship.cpp
        hl2/npc_combinegunship.cpp
        hl2/npc_combines.cpp
        hl2/npc_cranedriver.cpp
        hl2/npc_crow.cpp
        hl2/npc_dog.cpp
        hl2/npc_eli.cpp
        hl2/npc_enemyfinder.cpp
        hl2/npc_fastzombie.cpp
        hl2/npc_fisherman.cpp
        hl2/npc_gman.cpp
        hl2/npc_headcrab.cpp
        episodic/npc_hunter.cpp
        hl2/npc_ichthyosaur.cpp
        hl2/npc_kleiner.cpp
        hl2/npc_launcher.cpp
        episodic/npc_magnusson.cpp
        hl2/npc_manhack.cpp
        hl2/npc_metropolice.cpp
        hl2/npc_monk.cpp
        hl2/npc_mossman.cpp
        hl2/npc_playercompanion.cpp
        hl2/npc_PoisonZombie.cpp
        hl2/npc_rollermine.cpp
        hl2/npc_scanner.cpp
        hl2/npc_stalker.cpp
        hl2/npc_strider.cpp
        npc_talker.cpp
        hl2/npc_turret_ceiling.cpp
        hl2/npc_turret_floor.cpp
        hl2/npc_turret_ground.cpp
        hl2/npc_vortigaunt_episodic.cpp
        hl2/npc_zombie.cpp
        hl2/npc_zombine.cpp
        hl2/point_apc_controller.cpp
        hl2/prop_combine_ball.cpp
        episodic/prop_scalable.cpp
        hl2/prop_thumper.cpp
        hl2/proto_sniper.cpp
        hl2/rotorwash.cpp
        hl2/script_intro.cpp
        ../shared/script_intro_shared.cpp
        hl2/vehicle_airboat.cpp
        hl2/vehicle_cannon.cpp
        hl2/vehicle_crane.cpp
        hl2/vehicle_jeep.cpp
        episodic/vehicle_jeep_episodic.cpp
        hl2/vehicle_prisoner_pod.cpp
        hl2/vehicle_viewcontroller.cpp
        hl2/weapon_357.cpp
        hl2/weapon_alyxgun.cpp
        hl2/weapon_annabelle.cpp
        hl2/weapon_ar2.cpp
        hl2/weapon_bugbait.cpp
        hl2/weapon_citizenpackage.cpp
        hl2/weapon_crossbow.cpp
        hl2/weapon_crowbar.cpp
        weapon_cubemap.cpp
        hl2/weapon_frag.cpp
        hl2/weapon_physcannon.cpp
        hl2/weapon_pistol.cpp
        hl2/weapon_rpg.cpp
        hl2/weapon_shotgun.cpp
        hl2/weapon_smg1.cpp
        episodic/weapon_striderbuster.cpp
        hl2/weapon_stunstick.cpp
        episodic/ep1_gamestats.cpp
        episodic/ep2_gamestats.cpp
        hl2/func_bulletshield.cpp
        episodic/npc_puppet.cpp

        # "unused"
        hl2/grenade_beam.cpp
        hl2/grenade_homer.cpp
        hl2/grenade_pathfollower.cpp
        hl2/npc_missiledefense.cpp
        hl2/vehicle_apc.cpp
        hl2/weapon_cguard.cpp
        hl2/weapon_flaregun.cpp
)
